import numpy as np
import pandas as pd


def generate_customer_data(n_customers=5000, seed=42):
    """Generate synthetic customer campaign data."""

    rng = np.random.default_rng(seed)

    data = pd.DataFrame({
        "customer_id": np.arange(1, n_customers + 1),
        "age": rng.integers(18, 70, n_customers),
        "income": rng.integers(20000, 120000, n_customers),
        "past_purchases": rng.poisson(5, n_customers),
        "website_visits": rng.poisson(4, n_customers),
        "customer_segment": rng.choice(
            ["new", "regular", "loyal"],
            n_customers,
            p=[0.3, 0.5, 0.2]
        ),
        "previous_discount": rng.choice(
            [0, 5, 10, 20],
            n_customers
        ),
    })

    # Current discount offered to the customer
    data["discount"] = rng.choice(
        [0, 5, 10, 20],
        n_customers
    )

    # Purchase probability
    purchase_score = (
        -2.0
        + 0.02 * data["website_visits"]
        + 0.10 * data["past_purchases"]
        + 0.03 * data["discount"]
        + 0.000005 * data["income"]
    )

    purchase_probability = 1 / (1 + np.exp(-purchase_score))

    data["purchase"] = rng.binomial(
        1,
        purchase_probability
    )

    # Revenue generated by the purchase
    data["revenue"] = (
        data["purchase"]
        * rng.uniform(50, 500, n_customers)
    ).round(2)

    return data


if __name__ == "__main__":
    df = generate_customer_data()

    output_path = "backend/data/customer_data.csv"
    df.to_csv(output_path, index=False)

    print(f"Generated {len(df)} customer records.")
    print(f"Saved to: {output_path}")
    print("\nFirst 5 rows:")
    print(df.head())